### PR TITLE
Add missing key events: play, pause, next, previous

### PR DESCRIPTION
**Pull request by henninghall**
Adds some missing key events for Android TV. Should be done equally for tvOS. 

@dlowder-salesforce How can set up a dev environment to test the changes locally? Is there an example project or similar?

### CODE REVIEW

**Comment by dlowder-salesforce** [comment]
@henninghall the new events don't exist on the Apple TV Siri remote, so I don't believe there is any need to add them on the tvOS native side.

To test the changes locally, you can build a RN Android app, or build the RNTester app in this repo, and then start an Android TV emulator from the AVD manager in Android Studio and run the app there.

**Comment by henninghall** [comment]
> @henninghall the new events don't exist on the Apple TV Siri remote, so I don't believe there is any need to add them on the tvOS native side.

Alright, great.

How do I test the changes in a custom RN app, just changing the src files doesn't seem to make it. Is there some kind of build step involved? Also tried to run the RNTester app but ran into a build error. Am I suppose to follow these steps? https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.63.3/RNTester/README.md

If you could help me test this change or make a release it would be appreciated 🙏  

The default D-pad on the emulator doesn't have a play or pause button, only the "play/pause". But you can test it by running these commands and make sure an event is emitted to the javascript layer. 

Play:
```adb shell input keyevent 126```

Pause:
```adb shell input keyevent 127```

**Comment by dlowder-salesforce** [comment]
For Android, you need to do these steps:
- Pull the RN branch with the changes you want to test (https://github.com/henninghall/react-native-tvos/tree/patch-1)
- Change to that directory and execute `yarn` to install dependencies
- Execute `./gradlew :ReactAndroid:installArchives` to build the `android` directory with the Maven files that would be generated for a release
- Copy that new `android` directory to `node_modules/react-native` in your test project, replacing the existing `android` directory
- Rebuild the Android binary for your test project (or do `react-native run-android`) to pick up the changes

**Comment by henninghall** [comment]
Great, thanks for the guide. I've tested the changes now and they work just fine!

**Review by dlowder-salesforce — APPROVED** [review]

**Comment by henninghall** [comment]
@dlowder-salesforce When do you think this could be released? 🙂

**Comment by dlowder-salesforce** [comment]
@henninghall I'll push out a release next week, it will be 0.63.4 based and include this fix.

**Comment by henninghall** [comment]
Great!

**Comment by dlowder-salesforce** [comment]
@henninghall release 0.63.4-0 is out, including this fix, and core updates from core version 0.63.4.

**Pull request merged**
