### PR TITLE
refactor: tvfocusguideview component and documentation

### PR DESCRIPTION
**Pull request by leonchabbey**
## Summary

Small refactor of the TVFocusGuideView following the merges of our PRs https://github.com/react-native-tvos/react-native-tvos/pull/313 and https://github.com/react-native-tvos/react-native-tvos/pull/314.

And added some documentation about TVFocusGuideView in the README.

### CODE REVIEW

**Review by douglowder — CHANGES_REQUESTED** [review]
Thanks VERY much for the documentation additions and Typescript types!

I would ask that your refactor be done only on `TVFocusGuideView.android.js`, and leave `TVFocusGuideView.js` as is.

**Comment by leonchabbey** [comment]
May i ask why you want separate files split per platform for TVFocusGuideView?

The way I refactored it avoid a lot of code duplication, is a cleaner implementation overall (IMO 😃) and at the same time highlights the differences on how the `destinations` prop is handled on tvOS and Android TV.

For example, the file split you did added [a regression](https://github.com/react-native-tvos/react-native-tvos/blob/tvos-v0.68.2/Libraries/Components/AppleTV/TVFocusGuideView.android.js#L70) on Android, the padding is not overridden on the container, which would have been avoided with this refactor.

**Comment by douglowder** [comment]
I thought I tested the Android implementation with the new RNTester example and verified that the padding worked as expected. It is actually not supposed to be applied to the container, but to the contents, so I am not convinced that there is a regression :)

The reason I split the files is that I intend in the near future to unify them using the same pattern as the Apple TV implementation, via `Commands.setDestinations(nativeDestinations)`, so that everything works better with the Fabric architecture. However, I agree that this should be possible with your unified implementation as well.

I'll do some testing of your changes and then go ahead and merge.

**Review by douglowder — APPROVED** [review]
Thanks VERY much for the documentation additions and Typescript types!

I would ask that your refactor be done only on `TVFocusGuideView.android.js`, and leave `TVFocusGuideView.js` as is.

**Comment by leonchabbey** [comment]
Sorry, the "regression" I was talking about is that if someone passes padding through the style prop, it will be also applied to the container because we are not overriding the paddingTop, paddingBottom, ... like we do for margins. I fixed that with [this change](https://github.com/react-native-tvos/react-native-tvos/pull/314/files#diff-8a312b8d2f6629fa4245b2aa7af7d1dc779997f031dc858bb5a96031e5706cd5R88-R91) and I saw you didn't do the same for Android :)

And thanks for the explanation about the future changes you have in mind! I agree with you, the more the platform implementations are similar the better!

**Pull request merged**
