### PR TITLE
feat: [Apple TV]  add remote arrow buttons support to TVTextScrollView

### PR DESCRIPTION
**Pull request by dratwas**
## Summary:

This pull request introduces enhanced functionality to the TVTextScrollView on the tvOS platform by incorporating support for remote arrow controls. Currently, the TVTextScrollView exclusively relies on swipe gestures, a divergence from the functionality on the Android platform. With this update, users will now be able to seamlessly scroll through text within the ScrollView using remote buttons on both platforms.

Additionally, this pull request addresses a specific issue related to scrolling when there are other focusable components surrounding the TVTextScrollView. The video demonstration revealed an impediment to vertically scrolling the text when buttons were positioned below the ScrollView. Instead of allowing smooth scrolling, the focus shifted to the button below. This update rectifies this issue, ensuring a more intuitive and user-friendly scrolling experience in such scenarios.

https://github.com/react-native-tvos/react-native-tvos/assets/16336501/017350a0-2003-43e3-86c0-16fc78299791

## Changelog:
```
- [tvOS] [Added] - add support for arrow remote buttons in TVTextScrollView component
- [tvOS] [Fixed] - fix scrolling of TVTextScrollView when there are other focusable components surrounding it
```

## Test Plan:

There are two things to check in this PR.

### 1. Check if a remote arrow buttons scroll the TVTextScrollView content

**Before**

https://github.com/react-native-tvos/react-native-tvos/assets/16336501/5578b807-64ec-4a25-895b-25d751a5c043

**After**

https://github.com/react-native-tvos/react-native-tvos/assets/16336501/acc356f3-3e0f-42f6-801d-7454be12c62d

### 2. Check if scrolling is possible when there are other focusable components around

**Before**

https://github.com/react-native-tvos/react-native-tvos/assets/16336501/80c358e8-f24a-4e6d-a875-ce280228249f

**After**

https://github.com/react-native-tvos/react-native-tvos/assets/16336501/1ed29595-0b25-4b9a-8f1b-8a15bb4aff62

## Additional note
I couldn't find support for TVTextScrollView in the Fabric ScrollView component. We (@callstack) will add it soon ;)

### CODE REVIEW

**Review by douglowder — APPROVED** [review]

**Comment by christianEconify** [comment]
@douglowder 
This PR breaks scrollViews and Flatlists on RTL.

You can't focus left or right out of a horizontal flat list when the contentSize exceeds the viewableSize. 

```

the below fixes the issue 95% of the time, but it can occur sometimes when quickly going left and then right across a flat list. 

removing the function completely also has around a 95% success rate.
I've managed to reproduce in RNTester also, will be detailing this more in an issue soon

- (BOOL)shouldUpdateFocusInContext:(UIFocusUpdateContext *)context
{
    // Determine if the layout is Right-to-Left
    BOOL isRTL = [[RCTI18nUtil sharedInstance] isRTL];
    NSLog(isRTL ? @"isRTL" : @"isntRTL");
    // Adjust for horizontal scrolling with RTL support
    if ([self isHorizontal:self.scrollView]) {
        BOOL isNavigatingToEnd = (isRTL ? context.focusHeading == UIFocusHeadingLeft : context.focusHeading == UIFocusHeadingRight);
        BOOL isNavigatingToStart = (isRTL ? context.focusHeading == UIFocusHeadingRight : context.focusHeading == UIFocusHeadingLeft);
        
        if ((isNavigatingToEnd && self.scrollView.contentOffset.x < self.scrollView.contentSize.width - self.scrollView.visibleSize.width) ||
            (isNavigatingToStart && self.scrollView.contentOffset.x > 0)) {
            return [UIFocusSystem environment:self containsEnvironment:context.nextFocusedItem];
        }
    } else {
        // Handle vertical scrolling as before
        if ((context.focusHeading == UIFocusHeadingUp && self.scrollView.contentOffset.y > 0) ||
            (context.focusHeading == UIFocusHeadingDown && self.scrollView.contentOffset.y < self.scrollView.contentSize.height - self.scrollView.visibleSize.height)) {
            return [UIFocusSystem environment:self containsEnvironment:context.nextFocusedItem];
        }
    }
    
    return [super shouldUpdateFocusInContext:context];
}

```

**Comment by douglowder** [comment]
@christianEconify thanks for the report! Does Android TV have the same problem? @yusufyildirim

**Comment by christianEconify** [comment]
@douglowder AndroidTV does not face the same problem, But it does face an issue with autoFocus on RTL. An issue I'll be raising in a few days. It picks the left most item rather than right. (but I'm going off topic :) )

**Comment by douglowder** [comment]
Since you are testing with RNTester, does this also happen with new arch enabled?

**Comment by christianEconify** [comment]
To get RNTester up and running I ran
`yarn setup-ios-hermes`
and then yarn start after building in Xcode

I see the following output from metro

```
 (NOBRIDGE) LOG  Bridgeless mode is enabled
 (NOBRIDGE) LOG  Running "RNTesterApp" with {"rootTag":1,"initialProps":{"concurrentRoot":true},"fabric":true}
```

So I believe YES?

**Comment by christianEconify** [comment]
I've linked my RNTester changes in the Issue

**Pull request merged**
